const data = [
  {
    id: "1",
    avatar: "./images/avatar-mark-webber.png",
    name: "Mark Webber",
    action: "reacted to your recent post",
    post: "My first tournament today!",
    time: "1m ago",
  },
  {
    id: "2",
    avatar: "./images/avatar-angela-gray.png",
    name: "Angela Gray",
    action: "Followed you",
    post: "",
    time: "5m ago",
  },
  {
    id: "3",
    avatar: "./images/avatar-jacob-thompson.png",
    name: "Jacob Thompson",
    action: "has joined your group",
    post: "Chess club",
    time: "1 day ago",
  },
  {
    id: "4",
    avatar: "./images/avatar-rizky-hasanuddin.png",
    name: "Rizky Hasanuddin",
    action: "sent you a private message",
    time: "5 days ago",
    post: "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and i I'm already having lots of fun and improving my game.",
  },
  {
    id: "5",
    avatar: "./images/avatar-kimberly-smith.png",
    name: "Kimberly Smith",
    action: "commented on your picture",
    post: "./images/image-chess.png",
    time: "1 week ago",
  },
  {
    id: "6",
    avatar: "./images/avatar-nathan-peterson.png",
    name: "Nathan Peterson",
    action: "reacted to your recent post",
    post: "5 end-game strategies to increase your win rate",
    time: "2 weeks ago",
  },
  {
    id: "7",
    avatar: "./images/avatar-anna-kim.png",
    name: "Anna Kim",
    action: "left the group",
    post: "Chess Club",
    time: "2 weeks ago",
  },
];

export default data;
